name: build-custom-release
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: "The branch to deploy"
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "${{ github.event.inputs.branch }}"
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master
      - name: Get version
        run: |
          VERSION=$(cat src/main/resources/version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Building $VERSION"
      - name: Build
        run: mvn --no-transfer-progress compile
      - name: Test
        run: mvn --no-transfer-progress test
      - name: Package
        run: mvn --no-transfer-progress package -DskipTests
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build/Push Docker Images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            shayaantx/botdarr:${{ env.VERSION }}
      - name: Creater builder
        run: |
          docker buildx version
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multiarch --driver docker-container --use
          docker buildx inspect --bootstrap