name: development
on:
  push:
    branches:
    - 'development'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
        version: latest
        driver-opts: image=moby/buildkit:master
    - name: Get version
      run: |
        VERSION=$(cat src/main/resources/version.txt)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Building $VERSION"
    - name: Build
      run: mvn --no-transfer-progress compile
    - name: Test
      run: mvn --no-transfer-progress test
    - name: Package
      run: mvn --no-transfer-progress package -DskipTests
    - name: Create Github Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: ${{ env.VERSION }}
        body: |
          ${{ env.GITHUB_SHA }}
        draft: false
        prerelease: false
    - name: Upload Artifact to Github Release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/botdarr-release.jar
        asset_name: botdarr-release.jar
        asset_content_type: application/jar
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          shayaantx/botdarr:latest
          shayaantx/botdarr:${{ env.VERSION }}