name: pull-request
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: "${{ github.event.pull_request.merge_commit_sha }}"
    - name: Setup java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Get version
      run: |
        VERSION=$(cat src/main/resources/version.txt)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Building $VERSION"
    - name: Build
      run: mvn --no-transfer-progress compile
    - name: Test
      run: mvn --no-transfer-progress test
    - name: Package
      run: mvn --no-transfer-progress package -DskipTests